# Generated by Django 4.0.5 on 2022-07-05 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_alter_profile_options_rename_adout_profile_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='photos/user.png', null=True, upload_to='photos/', verbose_name='Фотография пользователя'),
        ),
        migrations.CreateModel(
            name='UserFollowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_user_id', models.ManyToManyField(related_name='follow_user_id', to=settings.AUTH_USER_MODEL)),
                ('following_user_id', models.ManyToManyField(related_name='following_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
