# Generated by Django 4.0.5 on 2022-07-05 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0004_alter_profile_profile_pic_userfollowing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollowing',
            name='follow_user_id',
        ),
        migrations.AddField(
            model_name='userfollowing',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='userfollowing',
            name='following_user_id',
        ),
        migrations.AddField(
            model_name='userfollowing',
            name='following_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
