# Generated by Django 4.0.5 on 2022-07-05 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_userfollowing_follow_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollowing',
            old_name='following_user_id',
            new_name='following_user',
        ),
        migrations.RenameField(
            model_name='userfollowing',
            old_name='user_id',
            new_name='user',
        ),
    ]
